// Core icon utilities
export { createIcon, getIconSize, iconSizes } from "./Icon";
export type { IconProps, IconSize } from "./Icon";

// Icons - Alphabetically ordered
export { AllServicesIcon } from "./icons/AllServicesIcon";
export { AppleIcon } from "./auth/AppleIcon";
export { ArrowRightIcon } from "./icons/ArrowRightIcon";
export { ArrowUpRightIcon } from "./icons/ArrowUpRightIcon";
export { BadgeCheckIcon } from "./icons/BadgeCheckIcon";
export { BookingsIcon } from "./icons/BookingsIcon";
export { CalenderIcon } from "./icons/CalenderIcon";
export { CheckCircleIcon } from "./icons/CheckCircleIcon";
export { CheckIcon } from "./icons/CheckIcon";
export { CheckSimpleIcon } from "./icons/CheckSimpleIcon";
export { ChevronDownIcon } from "./icons/ChevronDownIcon";
export { ChevronRightIcon } from "./icons/ChevronRightIcon";
export { ClipboardIcon } from "./icons/ClipboardIcon";
export { ClockIcon } from "./icons/ClockIcon";
export { CloseIcon } from "./icons/CloseIcon";
export { DangerIcon } from "./icons/DangerIcon";
export { DocumentIcon } from "./icons/DocumentIcon";
export { DownloadIcon } from "./icons/DownloadIcon";
export { DryWallIcon } from "./icons/DryWallIcon";
export { EmailIcon } from "./icons/EmailIcon";
export { EyeIcon } from "./icons/EyeIcon";
export { EyeOffIcon } from "./icons/EyeOffIcon";
export { FinalIcon } from "./icons/FinalIcon";
export { FramingIcon } from "./icons/FramingIcon";
export { GoogleIcon } from "./auth/GoogleIcon";
export { HandymanIcon } from "./icons/HandymanIcon";
export { HeartHandIcon } from "./icons/HeartHandIcon";
export { HomeIcon } from "./icons/HomeIcon";
export { HvacIcon } from "./icons/HvacIcon";
export { IncreaseIcon } from "./icons/IncreaseIcon";
export { InfoCircleIcon } from "./icons/InfoCircleIcon";
export { JobsIcon } from "./icons/JobsIcon";
export { InstagramIcon } from "./icons/InstagramIcon";
export { LinkedInIcon } from "./icons/LinkedInIcon";
export { LocationIcon } from "./icons/LocationIcon";
export { LockIcon } from "./icons/LockIcon";
export { MessageIcon } from "./icons/MessageIcon";
export { MinusIcon } from "./icons/MinusIcon";
export { PermitIcon } from "./icons/PermitIcon";
export { PhoneIcon } from "./icons/PhoneIcon";
export { PlusIcon } from "./icons/PlusIcon";
export { QuestionIcon } from "./icons/QuestionIcon";
export { SearchIcon } from "./icons/SearchIcon";
export { SettingsIcon } from "./icons/SettingsIcon";
export { ShieldCheckIcon } from "./icons/ShieldCheckIcon";
export { ShieldIcon } from "./icons/ShieldIcon";
export { SparkleIcon } from "./icons/SparkleIcon";
export { StarFilledIcon } from "./icons/StarFilledIcon";
export { StarIcon } from "./icons/StarIcon";
export { ThermometerIcon } from "./icons/ThermometerIcon";
export { ThunderIcon } from "./icons/ThunderIcon";
export { TikTokIcon } from "./icons/TikTokIcon";
export { ToolsIcon } from "./icons/ToolsIcon";
export { TrashIcon } from "./icons/TrashIcon";
export { UsersIcon } from "./icons/UsersIcon";
export { VerifiedIcon } from "./icons/VerifiedIcon";
export { WaterIcon } from "./icons/WaterIcon";
export { XIcon } from "./icons/XIcon";
export { YouTubeIcon } from "./icons/YouTubeIcon";

// Dashboard Icons
// export { DashboardIcon } from "./dashboard/DashboardIcon";
export { DashboardIcon } from "./icons/DashboardIcon";
export { LogoutIcon } from "./dashboard/LogoutIcon";
export {SearchDashboardIcon} from "./dashboard/SearchIcon";

